version: "3"

services:
  api:  
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_NEV: 'development'
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"

